#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyserial
Version  : 2.7
Release  : 7
URL      : https://pypi.python.org/packages/source/p/pyserial/pyserial-2.7.tar.gz
Source0  : https://pypi.python.org/packages/source/p/pyserial/pyserial-2.7.tar.gz
Summary  : Python Serial Port Extension
Group    : Development/Tools
License  : Python-2.0
Requires: pyserial-bin
Requires: pyserial-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
==========
pySerial
==========
Overview
========
This module encapsulates the access for the serial port. It provides backends
for Python running on Windows, Linux, BSD (possibly any POSIX compliant
system), Jython and IronPython (.NET and Mono). The module named "serial"
automatically selects the appropriate backend.

%package bin
Summary: bin components for the pyserial package.
Group: Binaries

%description bin
bin components for the pyserial package.


%package python
Summary: python components for the pyserial package.
Group: Default

%description python
python components for the pyserial package.


%prep
%setup -q -n pyserial-2.7

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
cd test ; python run_all_tests.py || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/miniterm.py

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
