#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyserial
Version  : 3.5
Release  : 42
URL      : https://files.pythonhosted.org/packages/1e/7d/ae3f0a63f41e4d2f6cb66a5b57197850f919f59e558159a4dd3a818f5082/pyserial-3.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/7d/ae3f0a63f41e4d2f6cb66a5b57197850f919f59e558159a4dd3a818f5082/pyserial-3.5.tar.gz
Summary  : Python Serial Port Extension
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyserial-bin = %{version}-%{release}
Requires: pyserial-license = %{version}-%{release}
Requires: pyserial-python = %{version}-%{release}
Requires: pyserial-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=================================
pySerial  |build-status| |docs|
=================================

%package bin
Summary: bin components for the pyserial package.
Group: Binaries
Requires: pyserial-license = %{version}-%{release}

%description bin
bin components for the pyserial package.


%package license
Summary: license components for the pyserial package.
Group: Default

%description license
license components for the pyserial package.


%package python
Summary: python components for the pyserial package.
Group: Default
Requires: pyserial-python3 = %{version}-%{release}

%description python
python components for the pyserial package.


%package python3
Summary: python3 components for the pyserial package.
Group: Default
Requires: python3-core
Provides: pypi(pyserial)

%description python3
python3 components for the pyserial package.


%prep
%setup -q -n pyserial-3.5
cd %{_builddir}/pyserial-3.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1610378321
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyserial
cp %{_builddir}/pyserial-3.5/LICENSE.txt %{buildroot}/usr/share/package-licenses/pyserial/2e9551f0a7f774587d80570697b32611b3191d35
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyserial-miniterm
/usr/bin/pyserial-ports

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyserial/2e9551f0a7f774587d80570697b32611b3191d35

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
